### ISSUE TITLE
Accept EULA via POST /api/v2/products/:product_slug/releases/:release_id/eula_acceptance

### ISSUE THREAD

**Issue by cantzakas** [cantzakas/gpdb-packaging#13]

**Comment by davidje13** [comment]
We need to decide what to do with the eula in general. VirtualBox has the ability to include a license with the VM which must be accepted before running, so we could copy the EULA into that field and auto-accept from pivnet. I guess it would also be important to make sure the user knows this is happening, because it will accept the EULA for that product on their account permanently.

**Comment by davidje13** [comment]
I have added an option:

* (default) auto-accept the pivnet EULA and copy it into the VM (the user of the VM then sees the EULA when importing and must accept it manually); or

* print the EULA to the console and ask explicitly for acceptance, then do *not* copy it into the VM

I think this should meet the legal requirements while making things a bit more automated.

Sadly, pivnet doesn't have an API to check if the user has accepted a EULA (other than trying a download and checking the error), so the second option will ask every time.
